sudo: require
services:
- docker
before_install:
- docker pull node:8-onbuild
install:
- docker build -t probot-hello .
script:
- docker run --rm probot-hello npm run test
- docker run --rm probot-hello npm run lint
deploy:
  provider: heroku
  api_key:
    secure: iNGaGjvv0XBt6Rk4H9IGtUH5XlKICS3HdHrtzqYCHh3XSJ2AhKYhIp18DHYcmXPL2Zr+MJuGvBZSC1tOk4GKPi7gBN+QwkX4MuBljKYBIm8cTiHfBRcXBao5SpVhDFWxACf5MSIqgqXGHZpGrg1Nh9RKbGVuZmEeUe8eRAvAar6UKhnHlB/nI7A504a59DcZ1nMLkr/E5kY09IMN9BBormdAjwE0xjges6vTJFGRbst9/AWFrtultsHra1K4VvXrIXLK5t+0PTG9CuLWLIDqoBv5FsTaOH0g8S2jbfBPUpoCWa/XZwNOcs5A+58pMo5a+2MbyZwG26dT+6wLLwHUdc3Sak3zkFDtF3Qy7p/EUMTHqp0tA9Lk1Xe577uLGySUPMLUkmhvQbzm292Yehjic0BK5OrmqnV4gSKHc/229JKCSFRvXktIiEUE7kxbGJSXm+QyPa5j4Of2FFnhf5CxD+CofaWS6esYn6NpY5fn5hKbUel+CXzQZTDSRH0qYRSiytmtgKVaJYStsYzyapcb2KsuK0l7Xd+8FiFvWKvCGGyA57k5veqpPXcvp2m4KCUVzfZkFo/4iy3a31q9RBsIK0tf1zby2f6nIkk0DosUASJcV1e/cCc8yRAeaZNHwb9LzXeUy1Xwn23wfk2KC2KmVYnsFX5bYsdJgn62dtZ4h9A=
  on: heroku_production
  app: probot-wenlockca
