version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build_and_test:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - node/install:
          node-version: '8-onbuild' 
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run build
          name: Build app        

workflows:
  example-workflow:
    jobs:
      - build_and_test
