version: 2.1
jobs:
  build_and_test: # this can be any name you choose
    docker:
      - image: circleci/node:8-onbuild
    steps:
      - checkout
      - run:
          command: npm install
          name: Install dependencies
      - run:
          command: npm run build
          name: Build app        
      - run:
          command: npm run test
          name: Test app
workflows:
  example-workflow:
    jobs:
      - build_and_test
